#!/usr/bin/env bash

FILE_NAME="cuckoo_generator.app"
cd Generator
rm -rf Build
rm -rf "$FILE_NAME"
env -i PATH="$PATH" HOME="$HOME" xcodebuild -project 'CuckooGenerator.xcodeproj' -scheme 'CuckooGenerator' -configuration 'Release' CONFIGURATION_BUILD_DIR="$PWD/Build" clean build
mv Build/cuckoo_generator.app "$FILE_NAME"
cd ..
