#!/usr/bin/env bash

SCRIPT_PATH="`dirname \"$0\"`"
FILE_NAME=cuckoo_generator.app
FILE_PATH=$SCRIPT_PATH/Generator/$FILE_NAME
if [ ! -e $FILE_PATH ]; then
    CURRENT_PWD=$(pwd)
	cd $SCRIPT_PATH
	./build_generator
	cd $CURRENT_PWD
fi
INPUT_FILES=""
for (( i=0; i<SCRIPT_INPUT_FILE_COUNT; i++ ))
do
	VARIABLE=SCRIPT_INPUT_FILE_${i}
	INPUT_FILES+=" "${!VARIABLE}
done
$FILE_PATH/Contents/MacOS/cuckoo_generator "$@" ${INPUT_FILES}
