#!/usr/bin/env bash

SCRIPT_PATH="`dirname \"$0\"`"
FILE_NAME=cuckoo_generator.app
FILE_PATH=$SCRIPT_PATH/Generator/$FILE_NAME
if [ ! -e $FILE_PATH ]; then
    CURRENT_PWD=$(pwd)
	cd $SCRIPT_PATH
	./build_generator
	cd $CURRENT_PWD
fi

$FILE_PATH/Contents/MacOS/cuckoo_generator "$@"
