import Foundation

protocol PlainProtocolToTestNSObjectProtocolInheritance {
}

protocol ProtocolNotInheritingFromNSObjectProtocol {
}

protocol ProtocolInheritingFromNSObjectProtocol: NSObjectProtocol {
}

protocol ChildProtocolInheritingFromNSObjectProtocol: ProtocolInheritingFromNSObjectProtocol {
}

protocol ProtocolInheritingFromNSObjectProtocolUsingProtocolComposition: NSObjectProtocol & PlainProtocolToTestNSObjectProtocolInheritance {
}

protocol ChildProtocolInheritingFromNSObjectProtocolUsingProtocolComposition: ProtocolInheritingFromNSObjectProtocolUsingProtocolComposition {
}

protocol ProtocolInheritingFromNSObjectProtocolAndOtherProtocol: NSObjectProtocol, PlainProtocolToTestNSObjectProtocolInheritance {
}

protocol ChildProtocolInheritingFromNSObjectProtocolAndOtherProtocol: ProtocolInheritingFromNSObjectProtocolAndOtherProtocol {
}
